# config.v9+.yaml - configuration file for rnaseq-benchmark workflow
# using snakemake version 9.

executor: slurm
jobs: 20

default-resources:
    mem_mb: 10000
    slurm_account: chpc
    clusters: crystalpeak
    slurm_partition: crystalpeak-shared
    qos: crystalpeak
    runtime: '10 m'

set-threads:
    download_one_sample: 2
    align_one_sample: 4

