# config.v9+.yaml - configuration file for rnaseq-benchmark workflow
# using snakemake version 9.

executor: slurm
jobs: 20

default-resources:
    mem_mb: 10000
    slurm_account: chpc
    clusters: notchpeak
    slurm_partition: notchpeak-shared
    qos: notchpeak
    runtime: '10 m'

set-threads:
    download_one_sample: 2
    align_one_sample: 4

set-resources:
    download_one_sample:
        slurm_partition: notchpeak-dtn
        slurm_account: dtn
        qos: notchpeak-dtn
        runtime: '5 m'
        ntasks: 1

    align_one_sample:
        ntasks: 4
    
    download_annotation:
        slurm_partition: notchpeak-dtn
        slurm_account: dtn
        qos: notchpeak-dtn
        runtime: '5 m'
        ntasks: 1
    
    download_genome:
        slurm_partition: notchpeak-dtn
        slurm_account: dtn
        qos: notchpeak-dtn
        slurm_name: download_genome
        runtime: '5 m'
        ntasks: 1
